package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// expectedCommands lists every command the root tree should document.
// One file per entry, named <command path with spaces replaced by underscores>.md.
var expectedCommands = []string{
	"etude.md",
	"etude_bench.md",
	"etude_capture.md",
	"etude_gc.md",
	"etude_init.md",
	"etude_reindex.md",
	"etude_replay.md",
	"etude_retro_list.md",
	"etude_retro_show.md",
	"etude_run.md",
	"etude_run_list.md",
	"etude_run_show.md",
	"etude_sync.md",
}

func TestGeneratesOneFilePerCommand(t *testing.T) {
	dir := t.TempDir()
	if err := run(dir); err != nil {
		t.Fatalf("run: %v", err)
	}

	for _, name := range expectedCommands {
		path := filepath.Join(dir, name)
		if _, err := os.Stat(path); err != nil {
			t.Errorf("missing expected file: %s", name)
		}
	}
}

func TestFilesContainSynopsisAndFlags(t *testing.T) {
	dir := t.TempDir()
	if err := run(dir); err != nil {
		t.Fatalf("run: %v", err)
	}

	checks := map[string][]string{
		"etude.md":          {"## etude", "etude"},
		"etude_bench.md":    {"## etude bench", "bench"},
		"etude_run.md":      {"## etude run", "run"},
		"etude_run_list.md": {"## etude run list", "list"},
		"etude_run_show.md": {"## etude run show", "show"},
		"etude_init.md":     {"## etude init", "init"},
		"etude_capture.md":  {"## etude capture", "capture"},
		"etude_gc.md":       {"## etude gc", "gc"},
		"etude_replay.md":   {"## etude replay", "replay"},
		"etude_sync.md":     {"## etude sync", "sync"},
		"etude_reindex.md":  {"## etude reindex", "reindex"},
	}

	for file, terms := range checks {
		content, err := os.ReadFile(filepath.Join(dir, file))
		if err != nil {
			t.Errorf("cannot read %s: %v", file, err)
			continue
		}
		for _, term := range terms {
			if !strings.Contains(string(content), term) {
				t.Errorf("%s: expected to contain %q", file, term)
			}
		}
	}
}

func TestNoAutoGeneratedDateFooter(t *testing.T) {
	dir := t.TempDir()
	if err := run(dir); err != nil {
		t.Fatalf("run: %v", err)
	}

	entries, _ := filepath.Glob(filepath.Join(dir, "*.md"))
	for _, path := range entries {
		content, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		if strings.Contains(string(content), "Auto generated") {
			t.Errorf("%s contains 'Auto generated' footer — output is not deterministic", filepath.Base(path))
		}
	}
}

func TestDeterministicOutput(t *testing.T) {
	dir1 := t.TempDir()
	dir2 := t.TempDir()

	if err := run(dir1); err != nil {
		t.Fatalf("first run: %v", err)
	}
	if err := run(dir2); err != nil {
		t.Fatalf("second run: %v", err)
	}

	for _, name := range expectedCommands {
		a, err := os.ReadFile(filepath.Join(dir1, name))
		if err != nil {
			t.Errorf("missing from first run: %s", name)
			continue
		}
		b, err := os.ReadFile(filepath.Join(dir2, name))
		if err != nil {
			t.Errorf("missing from second run: %s", name)
			continue
		}
		if !bytes.Equal(a, b) {
			t.Errorf("%s differs between two runs — output is not deterministic", name)
		}
	}
}

func TestDriftGuard(t *testing.T) {
	// Locate the committed docs/cli directory relative to this file's module root.
	// We walk up from the test binary's working directory to find go.mod.
	committedDir, err := findCommittedCliDir()
	if err != nil {
		t.Skip("cannot locate committed docs/cli:", err)
	}

	dir := t.TempDir()
	if err := run(dir); err != nil {
		t.Fatalf("run: %v", err)
	}

	// Compare every expected file.
	for _, name := range expectedCommands {
		committed, err := os.ReadFile(filepath.Join(committedDir, name))
		if err != nil {
			t.Errorf("committed docs/cli/%s missing — run `make docs` to regenerate", name)
			continue
		}
		generated, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			t.Errorf("generated docs missing %s", name)
			continue
		}
		if !bytes.Equal(committed, generated) {
			t.Errorf("docs/cli/%s is stale — run `make docs` to regenerate", name)
		}
	}
}

// findCommittedCliDir resolves the docs/cli path by walking up from the
// test's working directory to find go.mod, then appending docs/cli.
func findCommittedCliDir() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	dir := wd
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return filepath.Join(dir, "docs", "cli"), nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	return "", os.ErrNotExist
}
