// Command gen-docs generates Markdown reference documentation for all etude CLI
// commands and writes them into the output directory.
//
// Usage:
//
//	go run ./cmd/gen-docs [-out <dir>]
//
// The output directory is cleaned of existing *.md files before generation so
// that stale pages from removed commands do not accumulate.
package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/joshuavial/etude/internal/cli"
	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

func main() {
	outDir := flag.String("out", "docs/cli", "directory to write generated docs into")
	flag.Parse()

	if err := run(*outDir); err != nil {
		fmt.Fprintln(os.Stderr, "gen-docs:", err)
		os.Exit(1)
	}
}

func run(outDir string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	if err := cleanMarkdownFiles(outDir); err != nil {
		return fmt.Errorf("clean output dir: %w", err)
	}

	root := cli.NewRootCommand(io.Discard, io.Discard)
	disableAutoGenTag(root)

	filePrepender := func(string) string {
		return "<!-- Code generated by gen-docs; DO NOT EDIT. Run `make docs` to regenerate. -->\n\n"
	}
	// linkHandler returns the filename unchanged — links stay relative within docs/cli/.
	linkHandler := func(s string) string { return s }

	if err := doc.GenMarkdownTreeCustom(root, outDir, filePrepender, linkHandler); err != nil {
		return fmt.Errorf("generate docs: %w", err)
	}

	n, err := countMarkdownFiles(outDir)
	if err != nil {
		return err
	}
	fmt.Printf("generated %d command docs into %s\n", n, outDir)
	return nil
}

// disableAutoGenTag walks the entire command tree (root and all descendants)
// and sets DisableAutoGenTag = true on each command so cobra never appends a
// dated "Auto generated by spf13/cobra on <date>" footer.
func disableAutoGenTag(cmd *cobra.Command) {
	cmd.DisableAutoGenTag = true
	for _, sub := range cmd.Commands() {
		disableAutoGenTag(sub)
	}
}

// cleanMarkdownFiles removes only GENERATED markdown files (those named
// "etude*.md" — the root command is "etude", so every generated page matches
// that prefix) without removing the directory itself. Scoping the glob to the
// generated prefix means that even if --out is mistakenly pointed at a directory
// containing hand-written docs (e.g. docs/, which holds run.md, bench.md,
// README.md — none of which start with "etude"), this never deletes them.
func cleanMarkdownFiles(dir string) error {
	entries, err := filepath.Glob(filepath.Join(dir, "etude*.md"))
	if err != nil {
		return err
	}
	for _, path := range entries {
		if err := os.Remove(path); err != nil {
			return err
		}
	}
	return nil
}

// countMarkdownFiles returns the number of generated "etude*.md" files in dir.
func countMarkdownFiles(dir string) (int, error) {
	entries, err := filepath.Glob(filepath.Join(dir, "etude*.md"))
	if err != nil {
		return 0, err
	}
	return len(entries), nil
}
